version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: cnpmjs.org
    volumes:
      - /home/docker/cnpm:/var/data/cnpm_data
    ports:
      - "5001:5001"
      - "5002:5002"
